from __future__ import annotations

from typing import Protocol
from uuid import UUID

from job_agent.domain.enums import ApprovalStatus, ResumeVisibility, VerificationStatus
from job_agent.domain.models import CareerProfile, Certification, Experience, JobAnalysis, JobOpportunity, Skill, TargetingPolicy
from job_agent.domain.jobs import JobMatchResponse, ParsedJobRequirement, RequirementCoverage
from job_agent.domain.retrieval import EvidenceRecord


class EvidenceRepository(Protocol):
    def get(self, identifier: UUID | str) -> EvidenceRecord | None: ...

    def list_records(
        self,
        *,
        experience_ids: list[UUID] | None = None,
        categories: list[str] | None = None,
        verification_statuses: list[VerificationStatus] | None = None,
        approval_statuses: list[ApprovalStatus] | None = None,
        resume_eligible: bool | None = None,
        resume_visibility: list[ResumeVisibility] | None = None,
    ) -> list[EvidenceRecord]: ...


class CareerRepository(Protocol):
    def get_profile(self) -> CareerProfile | None: ...
    def list_experiences(self) -> list[Experience]: ...
    def get_experience(self, experience_id: UUID) -> Experience | None: ...
    def list_skills(self) -> list[Skill]: ...
    def list_certifications(self) -> list[Certification]: ...


class JobRepository(Protocol):
    def get(self, job_id: UUID) -> JobOpportunity | None: ...
    def list(self, limit: int = 100) -> list[JobOpportunity]: ...
    def upsert(self, job: JobOpportunity, content_hash: str) -> tuple[JobOpportunity, bool]: ...
    def replace_requirements(self, job_id: UUID, requirements: list[ParsedJobRequirement]) -> list[ParsedJobRequirement]: ...
    def list_requirements(self, job_id: UUID) -> list[ParsedJobRequirement]: ...
    def save_analysis(
        self,
        analysis: JobAnalysis,
        *,
        stable_evidence_keys: list[str] | None = None,
        requirement_coverage: list[RequirementCoverage] | None = None,
        role_family: str | None = None,
        seniority: str | None = None,
        location_context: dict | None = None,
        confidence_context: dict | None = None,
    ) -> JobAnalysis: ...
    def latest_analysis(self, job_id: UUID) -> JobAnalysis | None: ...
    def latest_match_response(self, job_id: UUID) -> JobMatchResponse | None: ...


class PolicyRepository(Protocol):
    def get(self, policy_id: UUID) -> TargetingPolicy | None: ...
    def get_active(self) -> TargetingPolicy | None: ...
    def list(self) -> list[TargetingPolicy]: ...
    def add(self, policy: TargetingPolicy, active: bool = False) -> TargetingPolicy: ...
    def activate(self, policy_id: UUID) -> TargetingPolicy | None: ...
